=== CaioBindella/XSD-Validator/who_ictrp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="trials">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="trial" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="main" type="mainType"/>
              <xs:element name="contacts" type="contactsType"/>
              <xs:element name="countries" type="countriesType"/>
              <xs:element name="criteria" type="criteriaType"/>
              <xs:element name="health_condition_code" type="healthConditionCodeType"/>
              <xs:element name="health_condition_keyword" type="healthConditionKeywordType"/>
              <xs:element name="intervention_code" type="interventionCodeType"/>
              <xs:element name="intervention_keyword" type="interventionKeywordType"/>
              <xs:element name="primary_outcome" type="primaryOutcomeType"/>
              <xs:element name="secondary_outcome" type="secondaryOutcomeType"/>
              <xs:element name="secondary_sponsor" type="secondarySponsorType"/>
              <xs:element name="secondary_ids" type="secondaryIdsType"/>
              <xs:element name="source_support" type="sourceSupportType"/>
              <xs:element name="ethics_reviews" type="ethicsReviewsType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="mainType">
    <xs:sequence>
      <xs:element name="trial_id" type="xs:string"/>
      <xs:element name="utrn" type="xs:string" minOccurs="0"/>
      <xs:element name="reg_name" type="xs:string"/>
      <xs:element name="date_registration" type="xs:string"/>
      <xs:element name="primary_sponsor" type="xs:string"/>
      <xs:element name="public_title" type="xs:string"/>
      <xs:element name="acronym" type="xs:string" minOccurs="0"/>
      <xs:element name="scientific_title" type="xs:string"/>
      <xs:element name="scientific_acronym" type="xs:string" minOccurs="0"/>
      <xs:element name="date_enrolment" type="xs:string"/>
      <xs:element name="type_enrolment" type="xs:string"/>
      <xs:element name="target_size" type="xs:string"/>
      <xs:element name="recruitment_status" type="xs:string"/>
      <xs:element name="url" type="xs:string" minOccurs="0"/>
      <xs:element name="study_type" type="xs:string"/>
      <xs:element name="study_design" type="xs:string"/>
      <xs:element name="phase" type="xs:string"/>
      <xs:element name="hc_freetext" type="xs:string" minOccurs="0"/>
      <xs:element name="i_freetext" type="xs:string" minOccurs="0"/>
      <xs:element name="results_actual_enrolment" type="xs:string"/>
      <xs:element name="results_date_completed" type="xs:string"/>
      <xs:element name="results_url_link" type="xs:string"/>
      <xs:element name="results_summary" type="xs:string"/>
      <xs:element name="results_date_posted" type="xs:string"/>
      <xs:element name="results_date_first_publication" type="xs:string"/>
      <xs:element name="results_baseline_char" type="xs:string"/>
      <xs:element name="results_participant_flow" type="xs:string"/>
      <xs:element name="results_adverse_events" type="xs:string"/>
      <xs:element name="results_outcome_measures" type="xs:string"/>
      <xs:element name="results_url_protocol" type="xs:string"/>
      <xs:element name="results_IPD_plan" type="xs:string"/>
      <xs:element name="results_IPD_description" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="contactsType">
    <xs:sequence>
      <xs:element name="contact" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="middlename" type="xs:string"/>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country1" type="xs:string"/>
            <xs:element name="zip" type="xs:string"/>
            <xs:element name="telephone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="affiliation" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="countriesType">
    <xs:sequence>
      <xs:element name="country2" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="criteriaType">
    <xs:sequence>
      <xs:element name="inclusion_criteria" type="xs:string"/>
      <xs:element name="agemin" type="xs:string"/>
      <xs:element name="agemax" type="xs:string"/>
      <xs:element name="gender" type="xs:string"/>
      <xs:element name="exclusion_criteria" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="healthConditionCodeType">
    <xs:sequence><xs:element name="hc_code" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="healthConditionKeywordType">
    <xs:sequence><xs:element name="hc_keyword" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="interventionCodeType">
    <xs:sequence><xs:element name="i_code" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="interventionKeywordType">
    <xs:sequence><xs:element name="i_keyword" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="primaryOutcomeType">
    <xs:sequence><xs:element name="prim_outcome" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="secondaryOutcomeType">
    <xs:sequence><xs:element name="sec_outcome" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="secondarySponsorType">
    <xs:sequence><xs:element name="sponsor_name" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>

  <xs:complexType name="secondaryIdsType">
    <xs:sequence>
      <xs:element name="secondary_id" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="sec_id" type="xs:string"/>
            <xs:element name="issuing_authority" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sourceSupportType">
    <xs:sequence><xs:element name="source_name" type="xs:string" maxOccurs="unbounded"/></xs:sequence>
  </xs:complexType>

  <xs:complexType name="ethicsReviewsType">
    <xs:sequence>
      <xs:element name="ethics_review" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="approval_date" type="xs:string"/>
            <xs:element name="contact_name" type="xs:string"/>
            <xs:element name="contact_address" type="xs:string"/>
            <xs:element name="contact_phone" type="xs:string"/>
            <xs:element name="contact_email" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== CaioBindella/XSD-Validator/Guides/test_trial.xml
<?xml version="1.0" encoding="UTF-8"?>
<trials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="who_ictrp.xsd">
  <trial>
    <main>
      <trial_id>US-2026-001</trial_id>
      <utrn>U1111-1234-5678</utrn>
      <reg_name>United States Registry</reg_name>
      <date_registration>06/01/2026</date_registration>
      <primary_sponsor>Example University</primary_sponsor>
      <public_title>Public Study Title</public_title>
      <acronym>PST</acronym>
      <scientific_title>Full Scientific Title</scientific_title>
      <scientific_acronym>FST</scientific_acronym>
      <date_enrolment>01/02/2026</date_enrolment>
      <type_enrolment>Actual</type_enrolment>
      <target_size>100</target_size>
      <recruitment_status>Recruiting</recruitment_status>
      <url>http://example.com</url>
      <study_type>interventional</study_type>
      <study_design>Randomized</study_design>
      <phase>Phase 3</phase>
      <hc_freetext>Hypertension</hc_freetext>
      <i_freetext>Drug A</i_freetext>
      <results_actual_enrolment>0</results_actual_enrolment>
      <results_date_completed>01/01/2027</results_date_completed>
      <results_url_link>http://link.com</results_url_link>
      <results_summary>Summary pending</results_summary>
      <results_date_posted>01/02/2027</results_date_posted>
      <results_date_first_publication>01/03/2027</results_date_first_publication>
      <results_baseline_char>Baseline data</results_baseline_char>
      <results_participant_flow>Normal flow</results_participant_flow>
      <results_adverse_events>None</results_adverse_events>
      <results_outcome_measures>Primary measures</results_outcome_measures>
      <results_url_protocol>http://protocol.com</results_url_protocol>
      <results_IPD_plan>Yes</results_IPD_plan>
      <results_IPD_description>Anonymous data</results_IPD_description>
    </main>

    <contacts>
      <contact>
        <type>Scientific</type>
        <firstname>John</firstname>
        <middlename>Charles</middlename>
        <lastname>Smith</lastname>
        <address>123 Flower Street</address>
        <city>New York</city>
        <country1>United States</country1>
        <zip>10001</zip>
        <telephone>+12125550199</telephone>
        <email>john@example.com</email>
        <affiliation>NY University</affiliation>
      </contact>
    </contacts>

    <countries>
      <country2>United States</country2>
    </countries>

    <criteria>
      <inclusion_criteria>Healthy adults</inclusion_criteria>
      <agemin>18</agemin>
      <agemax>65</agemax>
      <gender>Both</gender>
      <exclusion_criteria>Pregnant women</exclusion_criteria>
    </criteria>

    <health_condition_code>
      <hc_code>I10</hc_code>
    </health_condition_code>

    <health_condition_keyword>
      <hc_keyword>High blood pressure</hc_keyword>
    </health_condition_keyword>

    <intervention_code>
      <i_code>A01</i_code>
    </intervention_code>

    <intervention_keyword>
      <i_keyword>Pharmacological</i_keyword>
    </intervention_keyword>

    <primary_outcome>
      <prim_outcome>Blood Pressure Reduction</prim_outcome>
    </primary_outcome>

    <secondary_outcome>
      <sec_outcome>Quality of life</sec_outcome>
    </secondary_outcome>

    <secondary_sponsor>
      <sponsor_name>National Science Foundation</sponsor_name>
    </secondary_sponsor>

    <secondary_ids>
      <secondary_id>
        <sec_id>NCT-123456</sec_id>
        <issuing_authority>ClinicalTrials.gov</issuing_authority>
      </secondary_id>
    </secondary_ids>

    <source_support>
      <source_name>Federal Government</source_name>
    </source_support>

    <ethics_reviews>
      <ethics_review>
        <status>Approved</status>
        <approval_date>10/01/2026</approval_date>
        <contact_name>Ethics Committee</contact_name>
        <contact_address>500 Main Ave</contact_address>
        <contact_phone>+12125550188</contact_phone>
        <contact_email>ethics@hospital.com</contact_email>
      </ethics_review>
    </ethics_reviews>
  </trial>
</trials>
